BlogProject/Models/ViewModels/ShowPostsViewModel.cs
using BlogProject.Models.Domain;
using BlogProject.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogAssignment.Models.ViewModels
{
    public class ShowPostsViewModel
    {
        public string Title { get; set; }
        public string Slug { get; set; }
        public string Body { get; set; }
        public bool Published { get; set; }
        public string UserId { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateUpdated { get; set; }
        public  List<ShowCommentViewModel> Comments { get; set; }
        public virtual ApplicationUser User { get; set; }
        public int PostId { get; set; }
        public string MediaUrl { get; set; }
    }
}

BlogProject/Controllers/CommentController.cs
using BlogAssignment.Controllers;
using BlogAssignment.Models;
using BlogProject.Models.Domain;
using BlogProject.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogProject.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private ApplicationDbContext DbContext;

        public CommentController()
        {
            DbContext = new ApplicationDbContext();
        }

        [HttpPost]
        public ActionResult Create(CreateCommentViewModel formData)
        {
            return SaveComment(null, formData);
        }
        private ActionResult SaveComment(int? id, CreateCommentViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Comment comment;
            if (!id.HasValue)
            {
                var userId = User.Identity.GetUserId();
                var user = DbContext.Users.FirstOrDefault(p => p.Id == userId);
                var post = DbContext.PostDatabase.FirstOrDefault(p => p.PostId == formData.PostId);

                if (post == null)
                {
                    return View();
                }

                comment = new Comment();
                comment.Body = formData.Body;

                comment.AuthorId = userId;               
                comment.UserId = userId;
                comment.User = user;

                DbContext.CommentDatabase.Add(comment);
                post.Comments.Add(comment);
            }
            else
            {
                comment = DbContext.CommentDatabase.FirstOrDefault(p => p.CommentId == id);
                if (comment == null)
                {
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }
                comment.Body = formData.Body;
                comment.ReasonOfUpdating = formData.ReasonOfUpdating;
                comment.DateUpdated = DateTime.Now;
            }
            DbContext.SaveChanges();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }
            string userId = User.Identity.GetUserId();
            var comment = DbContext.CommentDatabase.FirstOrDefault(p => p.CommentId == id);

            if (comment == null)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }

            var model = new CreateCommentViewModel();
            model.Body = comment.Body;
            model.ReasonOfUpdating = comment.ReasonOfUpdating;

            model.DateUpdated = comment.DateUpdated;


            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, CreateCommentViewModel formData)
        {
            return SaveComment(id, formData);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }
            string userId = User.Identity.GetUserId();
            var comment = DbContext.CommentDatabase.FirstOrDefault(p => p.CommentId == id && p.UserId == userId);
            if (comment != null)
            {
                DbContext.CommentDatabase.Remove(comment);
                DbContext.SaveChanges();
            }
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

    }

}

BlogProject/Controllers/HomeController.cs
using BlogAssignment.Models;
using BlogAssignment.Models.Domain;
using BlogAssignment.Models.ViewModels;
using BlogProject.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace BlogAssignment.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext DbContext;

        public HomeController()
        {
            DbContext = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            //var userId = User.Identity.GetUserId();
            var model = DbContext.PostDatabase
                .Select(p => new IndexPostViewModel
                {
                    Title = p.Title,
                    Slug = p.Slug,
                    Body = p.Body,
                    UserId = p.UserId,
                    Published = p.Published,
                    DateCreated = p.DateCreated,
                    DateUpdated = p.DateUpdated,
                    MediaUrl = p.MediaUrl,
                    User = p.User,
                    PostId = p.PostId
                }).ToList();
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            //PopulateViewBag();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(CreatePostViewModel formData)
        {
            return SavePost(null, formData);
        }

        private ActionResult SavePost(int? id, CreatePostViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            string fileExtension;

            //Validating file upload
            if (formData.Media != null)
            {
                fileExtension = Path.GetExtension(formData.Media.FileName);

                if (!Constants.AllowedFileExtensions.Contains(fileExtension))
                {
                    ModelState.AddModelError("", "File extension is not allowed.");

                    return View();
                }
            }
            string userId = User.Identity.GetUserId();

            Post post;

            if (!id.HasValue)
            {
                
                post = new Post();
                post.UserId = userId;
                post.Title = formData.Title;
                post.Slug = Post.MakeSlug(post.Title);
                var slug = post.Slug;
                bool duplicateSlug = DbContext.PostDatabase.Any(p => p.Slug == slug);
                if (duplicateSlug)
                {
                    var random = new Random().Next(1, 21);
                    post.Slug += "-" + random.ToString();
                }
                DbContext.PostDatabase.Add(post);
            }
            else
            {
                post = DbContext.PostDatabase.FirstOrDefault(p => p.PostId == id && p.UserId == userId);

                if (post == null)
                {
                    return RedirectToAction(nameof(HomeController.Index));
                }
            }
            post.Title = formData.Title;
            post.Body = formData.Body;
            post.Published = formData.Published;
            post.DateUpdated = DateTime.Now;

            if (formData.Media != null)
            {
                if (!Directory.Exists(Constants.MappedUploadFolder))
                {
                    Directory.CreateDirectory(Constants.MappedUploadFolder);
                }

                var fileName = formData.Media.FileName;
                var fullPathWithName = Constants.MappedUploadFolder + fileName;

                formData.Media.SaveAs(fullPathWithName);

                post.MediaUrl = Constants.UploadFolder + fileName;
            }

            DbContext.SaveChanges();

            return RedirectToAction(nameof(HomeController.Index));
        }



        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }
            string userId = User.Identity.GetUserId();
            var post = DbContext.PostDatabase.FirstOrDefault(p => p.PostId == id && p.UserId == userId);

            if (post == null)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }

            var model = new CreatePostViewModel();
            model.Title = post.Title;
            model.Body = post.Body;
           
            model.DateCreated = post.DateUpdated;
            model.MediaUrl = post.MediaUrl;

            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, CreatePostViewModel formData)
        {
            return SavePost(id, formData);
        }

        [HttpGet]
        public ActionResult fullDetail(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }
            
            var post = DbContext.PostDatabase.FirstOrDefault(p => p.PostId == id );
            if (post == null)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }
            var model = new ShowPostsViewModel()
            {
                PostId = id.Value,
                Title = post.Title,
                Body = post.Body,
                Comments = post.Comments.Select(p => new ShowCommentViewModel()
                {
                    Body = p.Body,
                    CommentId = p.CommentId,
                    UserId = p.UserId,
                    DateCreated = p.DateCreated,
                    DateUpdated = p.DateUpdated,
                    ReasonOfUpdating = p.ReasonOfUpdating,
                   
                    UserName = p.User.UserName
                }).ToList(),
            DateCreated = post.DateCreated,
                MediaUrl = post.MediaUrl
            };
            return View(model);
        }


        [HttpGet]
        [Route("myPost/{slug}")]
        public ActionResult DetailsByTitle(string slug)
        {
            if (string.IsNullOrWhiteSpace(slug))
            {
                return RedirectToAction(nameof(HomeController.Index));
            }
            
           
            var post = DbContext.PostDatabase.FirstOrDefault(p => p.Slug == slug );

            if (post == null)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }

            var model = new ShowPostsViewModel();
            model.PostId = post.PostId;
            model.Title = post.Title;
            model.Body = post.Body;
            model.Comments = post.Comments.Select(p => new ShowCommentViewModel()
            {
                Body = p.Body,
                DateCreated = p.DateCreated,
                DateUpdated = p.DateUpdated,
                CommentId = p.CommentId,
                ReasonOfUpdating = p.ReasonOfUpdating,
                UserName = p.User.UserName
            }).ToList();
            model.Published = post.Published;
            model.DateCreated = post.DateCreated;
            
            model.MediaUrl = post.MediaUrl;
            return View("FullDetail", model);

        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(HomeController.Index));
            }
            string userId = User.Identity.GetUserId();
            var post = DbContext.PostDatabase.FirstOrDefault(p => p.PostId == id && p.UserId == userId);
            if (post != null)
            {
                post.Comments.Clear();
                DbContext.PostDatabase.Remove(post);
                DbContext.SaveChanges();
            }
            return RedirectToAction(nameof(HomeController.Index));
        }

        [HttpGet]
        public ActionResult Search()
        {
            return View(new List<IndexPostViewModel>());
        }
        [HttpPost]
        public ActionResult Search(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                return RedirectToAction(nameof(HomeController.Index));
            }
            var search = query.ToLower();
            var model = DbContext.PostDatabase
                .Where(p => p.Title.ToLower().Contains(search) ||
                             p.Body.ToLower().Contains(search) ||
                             p.Slug.ToLower().Contains(search))

               .Select(p => new IndexPostViewModel
               {
                   Title = p.Title,
                   Slug = p.Slug,
                   Body = p.Body,
                   UserId = p.UserId,
                   Published = p.Published,
                   DateCreated = p.DateCreated,
                   DateUpdated = p.DateUpdated,
                   MediaUrl = p.MediaUrl,
                   User = p.User,
                   PostId = p.PostId
               }).ToList();
            if (!model.Any())
            {
                ModelState.AddModelError("", "No Result Found For Your Search");
                return View(model);
            }
            else if (!(User.IsInRole("Admin")))
            {
                model = model.Where(p => p.Published == true).ToList();
            }
            return View(model);
        }
    }
}

BlogProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BlogProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BlogProject/Views/Home/Create.cshtml
@model CreatePostViewModel
@{
    ViewBag.Title = "Create";
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script src="~/Scripts/Create.js"></script>
    

}

<h2>Create Post</h2>


<form method="post" enctype="multipart/form-data">
    @Html.ValidationSummary(false)

    <div class="form-group">
        @Html.LabelFor(p => p.Title, "Title:")
        @Html.TextBoxFor(p => p.Title, new { @class = "form-control", placeholder = "Title" })
    </div>

    

    <div class="form-group">
        @Html.LabelFor(p => p.Body, "Blog:")
        @Html.TextBoxFor(p => p.Body, new { @class = "form-control", placeholder = "Blog" })
    </div>

    <div class="form-group">
        <input type="file" name="Media" />
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Published, "Published")
        @Html.CheckBoxFor(p => p.Published, new { @class = "form-control" })

        <div class="">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>

    </div>

</form>

BlogProject/Views/Home/Edit.cshtml
@model CreatePostViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script src="~/Scripts/Create.js"></script>
}

    <form method="post" enctype="multipart/form-data">
        @Html.ValidationSummary(false)

        <div class="form-group">
            @Html.LabelFor(p => p.Title, "Post name:")
            @Html.TextAreaFor(p => p.Title, new { @class = "form-control", placeholder = "Post name" })
        </div>

        <div class="form-group">
            @Html.LabelFor(p => p.Body, "Post:")
            @Html.TextAreaFor(p => p.Body, new { id = "Body", @class = "form-control", placeholder = "Blog" })
        </div>
        <div class="form-group">
            <input type="file" name="Media" />
        </div>
        <div class="">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>

    </form>

BlogProject/Views/Home/FullDetail.cshtml
@model ShowPostsViewModel
@{
    ViewBag.Title = "FullDetail";
    //string Slug = Model.Title.ToLower();
    //Slug = Slug.Replace(" ", "-");
}

@section scripts {
    <script src="~/Scripts/Comment.js" type="text/javascript"></script>
}
<h2>Post</h2>

<td>@Html.Raw(Model.Body)</td>

@if (string.IsNullOrEmpty(Model.MediaUrl))
{
    <p>No Image</p>
}
else
{
    <div class="row">
        <div class="col-md-2">
            <img class="img-responsive" src="@Url.Content(Model.MediaUrl)" />
        </div>
    </div>

}



@if (!Model.Comments.Any())
{
    <div style="margin-top:15px;">
        <p><strong>You have no Comments</strong></p>
    </div>
}
else
{
    <div>

        <table class="table table-striped">
            
            <tbody>
                @foreach (var record in Model.Comments)
                {
                   
                        <tr>
                            <td>@record.Body</td>
                            <td>@record.UserName</td>
                            <td>@record.CommentId</td>
                            <td>@record.UserId</td>
                            <td>@record.ReasonOfUpdating</td>
                            <td>@record.DateCreated</td>
                            <td>@record.DateUpdated</td>
                            <td>

                                @if (User.IsInRole("Admin"))
                                {
                                    <a href="@Url.Action("Edit", "Comment", new { id = record.CommentId })">Edit</a>

                                    <form method="post" action="@Url.Action("Delete", "Comment", new { id = record.CommentId })">
                                        <a href="#" class="btn-delete">Delete</a>
                                    </form>
                                }
                            </td>
                        </tr>

                    

                }
            </tbody>
        </table>
    </div>
}  
    @if (User.Identity.IsAuthenticated)
    {
        <form action="@Url.Action("Create","Comment", new { PostId = Model.PostId })" method="post">
            <div class="form-group">
                <textarea name="Body"></textarea>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>}

BlogProject/Views/Home/Index.cshtml
@model List<IndexPostViewModel>


@{
    ViewBag.Title = "Home Page";
}

@section scripts {
    <script src="~/Scripts/index.js" type="text/javascript"></script>
}
<!-- Page Header -->
<header class="masthead" style=" background-image: url(@Url.Content(@"~/TemplateContent/img/home-bg.jpg"))">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<form action="@Url.Action("Search","Home", new {  })" method="post">
    <div class="form-group">
        <input type="text" placeholder="SearchPost" name="query" />
    </div>

</form>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <h4>List of Posts</h4>
            @if (User.IsInRole("Admin"))
            {
                <a class="btn btn-primary" href="@Url.Action("Create", "Home")">Upload a Post</a>
            }@if (!Model.Any())
            {
                <div style="margin-top:15px;">
                    <p><strong>You have no Posts</strong></p>
                </div>
            }
            else
            {
               



                foreach (var record in Model)
                {
                    if ((User.IsInRole("Admin")))
                    {
                        <hr>
                        <div class="post-preview">
                            
                                <h5 style="font-style:italic" class="post-title">
                                    @record.Title
                                </h5>

                           
                            <span class="post-meta">
                                Posted by
                                
                                    @record.User.UserName
                                on @record.DateCreated
                                Updated On @record.DateUpdated
                            </span>
                            <span class="post-meta">
                                @if (User.IsInRole("Admin"))
                                {
                                    <a href="@Url.Action("Edit", "Home", new { id = record.PostId })">Edit</a>
                                }
                            </span>
                            <span style="padding-left:4px" class="post-meta">
                                <a href="@Url.Action("DetailsByTitle", "Home", new { slug = record.Slug })">ReadMore....</a>
                            </span>
                            <div class="post-meta">
                                @if (User.IsInRole("Admin"))
                                {
                                    <form method="post" action="@Url.Action("Delete", "Home", new { id = record.PostId })">
                                        <a href="#" class="btn-delete">Delete</a>
                                    </form>}
                            </div>

                        </div>
                      
                    }
                    else if (record.Published == true && !(User.IsInRole("Admin")))
                    {

                        <hr>
                        <div class="post-preview">
                            
                                <h5 class="post-title">
                                    @record.Title
                                </h5>
                                <span class="post-meta">
                                    @record.Published 
                                    
                                </span>
                                <span class="post-meta">
                                    Published BY
                                    @record.User.UserName
                                    on @record.DateCreated
                                    Updated On @record.DateUpdated
                                </span>
                
                            
                           
                            <span>
                                <a href="@Url.Action("DetailsByTitle", "Home", new { slug = record.Slug })">ReadMore....</a>
                            </span>
                            <span>
                                @if (User.IsInRole("Admin"))
                                {
                                    <a href="@Url.Action("Edit", "Home", new { id = record.PostId })">Edit</a>
                                }
                            </span>
                            <div>
                                @if (User.IsInRole("Admin"))
                                {
                                    <form method="post" action="@Url.Action("Delete", "Home", new { id = record.PostId })">
                                        <a href="#" class="btn-delete">Delete</a>
                                    </form>}
                            </div>
                        </div>
                        
                    }
                }
                
            }

            <hr>
            <div class="clearfix">
                <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
            </div>
        </div>
    </div>
</div>
<hr>

<!--Post-->
<!--
<hr>
<div class="post-preview">
    <a href="post.html">
        <h2 class="post-title">
            Failure is not an option
        </h2>
        <h3 class="post-subtitle">
            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
        </h3>
    </a>
    <p class="post-meta">
        Posted by
        <a href="#">Start Bootstrap</a>
        on July 8, 2019
    </p>
</div>
-->

BlogProject/Views/Home/Search.cshtml
@model List<IndexPostViewModel>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<div>
    
    <hr />
    @if (Model.Any())
    {
   

        foreach (var record in Model)
        {
            <div class="post-preview">
                
                    <p class="post-title">
                        @record.Title
                    </p>
                    <p class="post-title">
                        @record.Published
                    </p>
                    <p class="post-meta">
                        Posted by
                        @record.User.UserName
                        on  @record.DateCreated
                        Edited on
                        @record.DateUpdated
                    </p>
            </div>
            
                @*<td>@record.Title</td>
                <td>@record.Published</td>
                <td>@record.User.UserName</td>
                <td>@record.DateCreated</td>
                <td>@record.DateUpdated</td>
            </tr>*@
        }
    
    }
</div>
<p>
    
    @Html.ActionLink("Back to List", "Index")
</p>

BlogProject/Views/Home/ShowPosts.cshtml
@model ShowPostsViewModel
@{
    ViewBag.Title = "ShowPosts";
}

<h2>Posts</h2>

<p>@Model.Title</p>
<p>@Model.Body</p>
<p>@Model.Published</p>